spring.application.name=ChurnGym

#Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/churngym
spring.datasource.username=churnadmin
spring.datasource.password=changeme

# JPA and Flyway config
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration